import { Content } from "@/types/IContent";

export const sampleContents: Content[] = [
  {
    id: "1",
    title: "Trilha de Programação Web",
    description:
      "Aprenda desde os fundamentos até frameworks modernos para desenvolvimento web.",
    category: "Programação",
    duration: "24h",
    level: "Iniciante ao Avançado",
    rating: 4.9,
    type: "trilha",
    isPremium: false,
    instructor: "Equipe de Instrutores",
    institution: "Universidade Federal de Tecnologia",
    thumbnail: "/javascript-course.png",
    totalHours: 24,
    totalCourses: 2,
    videosExtras: 5,
    podcasts: 2,
    articles: 4,
    instructors: [
      { name: "Maria Souza", avatar: "/prof1.png" },
      { name: "Fernanda Duarte", avatar: "/prof2.png" },
      { name: "Ricardo Mendes", avatar: "/prof3.png" },
    ],
    steps: [
      {
        title: "Primeiros passos em programação web",
        description: "Aprenda HTML, CSS e lógica de programação.",
      },
      {
        title: "Front-end avançado",
        description: "Aprofunde-se em JavaScript e frameworks modernos.",
      },
    ],
    courses: [
      {
        id: "c1",
        title: "HTML & CSS Básico",
        description: "Aprenda os fundamentos da web",
        progress: 100,
        duration: "6h",
        level: "Iniciante",
      },
      {
        id: "c2",
        title: "JavaScript Essencial",
        description: "Conceitos fundamentais de JavaScript",
        progress: 0,
        duration: "8h",
        level: "Intermediário",
      },
    ],
  },
  {
    id: "2",
    title: "Trilha de Data Science",
    description:
      "Domine análise de dados, estatística e machine learning com Python.",
    category: "Data Science",
    duration: "30h",
    level: "Intermediário ao Avançado",
    rating: 4.8,
    type: "trilha",
    isPremium: true,
    instructor: "Prof. Carlos Lima",
    institution: "Centro de Análise de Dados",
    thumbnail: "/python-data-science.png",
    totalHours: 30,
    totalCourses: 2,
    videosExtras: 8,
    podcasts: 3,
    articles: 6,
    instructors: [
      { name: "Carlos Lima", avatar: "/prof1.png" },
      { name: "Mariano Silva", avatar: "/prof2.png" },
      { name: "Gabriel Gomes", avatar: "/prof3.png" },
    ],
    steps: [
      {
        title: "Fundamentos de Data Science",
        description: "Estatística, Python e primeiros projetos.",
      },
      {
        title: "Machine Learning",
        description:
          "Modelos de aprendizado supervisionado e não supervisionado.",
      },
      {
        title: "Projetos Avançados",
        description: "Deploy, pipelines e aplicações reais.",
      },
    ],
    courses: [
      {
        id: "c3",
        title: "Introdução à Análise de Dados",
        description: "Primeiros passos em análise de dados com Python",
        progress: 0,
        duration: "10h",
        level: "Iniciante",
      },
      {
        id: "c4",
        title: "Machine Learning Básico",
        description: "Fundamentos de machine learning",
        progress: 0,
        duration: "12h",
        level: "Intermediário",
      },
    ],
  },
  {
    id: "3",
    title: "Trilha de Design UX/UI",
    description:
      "Do básico ao avançado em design de interfaces e experiência do usuário.",
    category: "Design",
    duration: "18h",
    level: "Iniciante ao Intermediário",
    rating: 4.7,
    type: "trilha",
    isPremium: false,
    instructor: "Prof. Ana Costa",
    institution: "Escola de Design Digital",
    thumbnail: "/ux-ui-design-course.png",
    totalHours: 18,
    totalCourses: 2,
    videosExtras: 4,
    podcasts: 2,
    articles: 3,
    instructors: [{ name: "Ana Costa", avatar: "/prof2.png" }],
    steps: [
      {
        title: "Fundamentos de UX",
        description: "Pesquisa, personas e fluxos.",
      },
      {
        title: "UI Avançado",
        description: "Estilos visuais, grids e prototipação.",
      },
    ],
    courses: [
      {
        id: "c5",
        title: "Fundamentos de UX",
        description: "Introdução à experiência do usuário",
        progress: 0,
        duration: "6h",
        level: "Iniciante",
      },
      {
        id: "c6",
        title: "UI Design Avançado",
        description: "Aprofundamento em design de interfaces",
        progress: 0,
        duration: "8h",
        level: "Avançado",
      },
    ],
  },
  {
    id: "4",
    title: "Trilha de Marketing Digital",
    description:
      "Aprenda estratégias e ferramentas essenciais para o marketing digital moderno.",
    category: "Marketing",
    duration: "12h",
    level: "Iniciante ao Intermediário",
    rating: 4.6,
    type: "trilha",
    isPremium: false,
    instructor: "Prof. Lucia Ferreira",
    institution: "Faculdade de Marketing Online",
    thumbnail: "/digital-marketing-strategy.png",
    totalHours: 12,
    totalCourses: 2,
    videosExtras: 3,
    podcasts: 1,
    articles: 2,
    instructors: [{ name: "Lucia Ferreira", avatar: "/instructors/lucia.png" }],
    steps: [
      { title: "Marketing Básico", description: "Conceitos e fundamentos." },
      {
        title: "SEO e SEM",
        description: "Técnicas de otimização e mídia paga.",
      },
    ],
    courses: [
      {
        id: "c7",
        title: "Introdução ao Marketing Digital",
        description: "Conceitos básicos e estratégias iniciais",
        progress: 0,
        duration: "4h",
        level: "Iniciante",
      },
      {
        id: "c8",
        title: "SEO e SEM",
        description: "Otimização para mecanismos de busca",
        progress: 0,
        duration: "6h",
        level: "Intermediário",
      },
    ],
  },
  {
    id: "5",
    title: "React Js do Básico ao Avançado",
    description: "Desenvolva aplicações web modernas utilizando React.js.",
    category: "Desenvolvimento Web",
    duration: "8h",
    level: "Iniciante ao Avançado",
    rating: 4.5,
    type: "trilha",
    isPremium: false,
    instructor: "Prof. Roberto Alves",
    institution: "Senac",
    thumbnail: "/react-advanced-course.png",
    totalHours: 8,
    totalCourses: 2,
    videosExtras: 2,
    podcasts: 1,
    articles: 1,
    instructors: [
      { name: "Roberto Alves", avatar: "/instructors/roberto.png" },
    ],
    steps: [
      { title: "React Básico", description: "JSX, componentes e props." },
      {
        title: "React Avançado",
        description: "Hooks, Context API e boas práticas.",
      },
    ],
    courses: [
      {
        id: "c9",
        title: "React Básico",
        description: "Primeiros passos com React",
        progress: 0,
        duration: "4h",
        level: "Iniciante",
      },
      {
        id: "c10",
        title: "React Avançado",
        description: "Hooks, Context API e mais",
        progress: 0,
        duration: "4h",
        level: "Avançado",
      },
    ],
  },
];
